name: car_share
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.2.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  formz: ^0.6.0
  go_router: ^7.1.1
  google_fonts: ^5.0.0
  provider: ^6.0.5
  riverpod: ^2.3.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
